In [1]:
import torch
from torch import nn

torch.cuda.is_available() # 输出 True

True

In [2]:
torch.cuda.device_count() # 输出 1

1

In [3]:
torch.cuda.current_device() # 输出 0

0

In [4]:
torch.cuda.get_device_name(0) # 输出 'GeForce GTX 1050'

'NVIDIA GeForce RTX 4060 Laptop GPU'

Tensor的GPU计算

In [5]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [6]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [7]:
x.device

device(type='cuda', index=0)

直接在创建的时候就指定设备。

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

如果对在GPU上的数据进行运算，那么结果还是存放在GPU上。

In [9]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

需要注意的是，存储在不同位置中的数据是不可以直接进行计算的。即存放在CPU上的数据不可以直接与存放在GPU上的数据进行运算，位于不同GPU上的数据也是不能直接进行计算的。

同Tensor类似，PyTorch模型也可以通过.cuda转换到GPU上。我们可以通过检查模型的参数的device属性来查看存放模型的设备。

In [10]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [11]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)